src/apps/about/urls.py
from django.conf.urls import url
from . import views


app_name = 'about'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

src/apps/album/urls.py
from django.conf.urls import url
from . import views


app_name = 'album'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

src/apps/blog/urls.py
from django.conf.urls import url
from libs.autoslug import ALIAS_REGEXP
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^by-tag/(?P<tag_slug>{0})/$'.format(ALIAS_REGEXP), views.IndexView.as_view(), name='tag'),
    url(r'^(?P<slug>{0})/$'.format(ALIAS_REGEXP), views.BlogDetailView.as_view(), name='detail'),
]

src/apps/contacts/urls.py
from django.conf.urls import url
from . import views


app_name = 'contacts'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^thank-you/$', views.SuccessView.as_view(), name='success'),
]

src/apps/disclaimer/urls.py
from django.conf.urls import url
from . import views


app_name = 'disclaimer'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

src/apps/faq/urls.py
from django.conf.urls import url
from . import views


app_name = 'faq'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

src/apps/main/urls.py
from django.conf.urls import url
from . import views


app_name = 'main'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

src/apps/policy/urls.py
from django.conf.urls import url
from . import views


app_name = 'policy'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

src/apps/services/urls.py
from django.conf.urls import url
from libs.autoslug import ALIAS_REGEXP
from . import views


app_name = 'services'
urlpatterns = [
    url(r'^(?P<parent_slug>{0})/(?P<slug>{0})/$'.format(ALIAS_REGEXP), views.ServiceView.as_view(), name='service'),
]

src/apps/shop/urls.py
from django.conf.urls import url
from libs.autoslug import ALIAS_REGEXP
from . import views


app_name = 'shop'
urlpatterns = [
    url(
        r'^$', views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^cart/$', views.CartView.as_view(),
        name='cart'
    ),
    url(
        r'^checkout/$', views.CheckoutView.as_view(),
        name='checkout'
    ),
    url(
        r'^payment/$', views.PaymentView.as_view(),
        name='payment'
    ),
    url(
        r'^payment/success/$', views.PaymentSuccessView.as_view(),
        name='payment_success'
    ),
    url(
        r'^(?P<category_slug>{0})/(?P<slug>{0})/$'.format(ALIAS_REGEXP),
        views.ProductView.as_view(),
        name='detail'
    ),
]

src/apps/team/urls.py
app_name = 'team'

src/apps/users/urls.py
from django.conf.urls import url
from . import views


app_name = 'users'
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^reset/$', views.PasswordResetView.as_view(), name='reset'),
    url(r'^reset_done/$', views.ResetDoneView.as_view(), name='reset_done'),
    url(r'^reset_confirm/$', views.ResetConfirmView.as_view(), name='reset_self'),
    url(r'^reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ResetConfirmView.as_view(), name='reset_confirm'),
    url(r'^reset_complete/$', views.ResetCompleteView.as_view(), name='reset_complete'),
    url(r'^reset_password/$', views.ResetConfirmView.as_view(), name='reset_password'),
]

src/apps_common/admin_ctr/urls.py
from django.conf.urls import url
from . import views


app_name = 'admin_ctr'
urlpatterns = [
    url(
        r'^add/(?P<content_type_id>\d+)/$',
        view=views.add_related,
        name='add_related'
    ),
    url(
        r'^change/(?P<content_type_id>\d+)/(?P<pk>\d+)/$',
        view=views.change_related,
        name='change_related'
    ),
    url(
        r'^delete/(?P<content_type_id>\d+)/(?P<pk>\d+)/$',
        view=views.delete_related,
        name='delete_related'
    ),
]

src/apps_common/ckeditor/urls.py
from django.conf.urls import url
from . import views


app_name = 'ckeditor'
urlpatterns = [
    url(r'^download_pagefile/(?P<file_id>\d+)/$', view=views.download_pagefile, name='download_pagefile'),
]

src/apps_common/constant_contact/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views
from .services import create_contact, get_contacts_lists, create_list

app_name = 'constant_contact'

urlpatterns = [
    url(r'^oauth/$', views.OAuthView.as_view(), name='oauth'),
    url(r'^callback/$', views.CallbackView.as_view(), name='callback'),
    url(r'^refresh/$', views.RefreshTokenView.as_view(), name='refresh'),
    url(r'^list/create/$', views.CreateListView.as_view(), name='create_list'),
    url(r'^create/$', create_contact, name='create'),
    url(r'^get-lists/$', get_contacts_lists, name='get_lists'),
]

src/apps_common/files/urls.py
from django.conf.urls import url
from . import views


app_name = 'files'
urlpatterns = [
    url(r'^download/(?P<file_id>\d+)/$', views.download, name='download'),
]

src/apps_common/paypal/urls.py
from django.conf.urls import url
from . import views


app_name = 'paypal'
urlpatterns = [
    url(r'^check/capture/$', views.check_capture, name='result'),
]

src/apps_common/shipstation/urls.py
from django.conf.urls import url
from . import webhooks


app_name = 'shipstation'
urlpatterns = [
    url(r'^webhook/$', webhooks.webhook, name='webhook'),
]

src/apps_common/social_networks/urls.py
import inspect
from django.conf.urls import url
from . import conf
from . import rss


app_name = 'social_networks'
urlpatterns = []

for name, member in inspect.getmembers(rss, predicate=inspect.isclass):
    if issubclass(member, rss.SocialRssFeed) and member.network in conf.ALLOWED_NETWORK_NAMES:
        urlpatterns.append(
            url(r'^rss/{}/$'.format(member.network), member(), name=member.network)
        )

src/libs/autocomplete/urls.py
from django.conf.urls import url
from . import views


app_name = 'autocomplete'
urlpatterns = [
    url(r'^filter/(?P<application>[\w.]+)/(?P<model_name>\w+)/$',
        view=views.autocomplete_filter,
        name='autocomplete_filter'
    ),

    url(r'^(?P<application>[\w.]+)/(?P<model_name>\w+)/(?P<name>[-\w]+)/$',
        view=views.autocomplete_widget,
        name='autocomplete_widget'
    ),
]

src/libs/sentry/urls.py
from django.conf.urls import url
from . import views


app_name = 'sentry'
urlpatterns = [
    url(r'^tunnel/$', view=views.tunnel, name='tunnel'),
]

src/apps_common/footer/templates/footer/footer.html
<footer itemscope itemtype="https://schema.org/WPFooter">
    <div class="grid-block">

        <div class="flex">
            <div class="flex__row">
                <div class="flex__column">
                    {% menu 'menu_footer' classes="menu--color-light menu--underline" item_id_mod='footer' %}
                </div>
            </div>
            <div class="flex__row">
                <div class="flex__column">
                    <div class="company" itemscope itemtype="https://schema.org/LocalBusiness">
                        <meta itemprop="name" content="{{ COMPANY }}">
                        <meta itemprop="legalName" content="{{ COMPANY }}">
                        <div itemprop="image" itemscope itemtype="https://schema.org/ImageObject" style="display: none !important;" >
                            <meta itemprop="url" content="{{ static('img/favicon.png') }}"/>
                        </div>

                        <div itemprop="address" itemscope itemtype="https://schema.org/PostalAddress" style="display: none !important;">
                            <meta itemprop="streetAddress" content="{{CONTACTS.address}}">
                            <meta itemprop="postalCode" content="{{ CONTACTS.zip }}">
                            <meta itemprop="addressRegion" content="{{CONTACTS.region}}">
                            <meta itemprop="addressLocality" content="{{ CONTACTS.city }}">
                        </div>

                        {% if CONTACTS.address or CONTACTS.str_city_address() %}
                            <div class="company__address">
                                {% if CONTACTS.address %}
                                    <span>{{ CONTACTS.address }}. </span>
                                {% endif %}

                                {% if CONTACTS.str_city_address() %}
                                    <span>{{ CONTACTS.str_region_address() }}</span>
                                {% endif %}
                            </div>
                        {% endif %}

                        {% if CONTACTS.phone or CONTACTS.email %}
                            <div class="company__contacts">
                                {% if CONTACTS.phone %}
                                    <div class="company__phone">
                                        <a href="tel:{{ CONTACTS.phone|phone }}" itemprop="telephone">{{ CONTACTS.phone }}</a>
                                    </div>
                                {% endif %}
                                {% if CONTACTS.email %}
                                    <div class="company__email">
                                        <a href="mailto:{{ CONTACTS.email }}" itemprop="email">{{ CONTACTS.email }}</a>
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="flex__column">
                    {% social_links classes='social-links--light social-links--right' %}
                </div>
            </div>
            <div class="flex__row">
                <div class="flex__column">
                    <div class="information">
                        <div class="information__copyright">
                            &copy; {{ str_copyright }}
                        </div>
                        {% if policy %}
                            {% if is_policy_page %}
                                <div class="information__policy">
                                    <span>{{ _('Privacy Policy') }}</span>
                                </div>
                            {% else %}
                                <div class="information__policy">
                                    <a href="{{ url('policy:index') }}">{{ _('Privacy Policy') }}</a>
                                </div>
                            {% endif %}
                        {% endif %}
                        {% if disclaimer %}
                            {% if is_disclaimer_page %}
                                <div class="information__disclaimer">
                                    <span href="{{ url('disclaimer:index') }}">{{ _('FDA Disclaimer') }}</span>
                                </div>
                            {% else %}
                                <div class="information__disclaimer">
                                    <a href="{{ url('disclaimer:index') }}">{{ _('FDA Disclaimer') }}</a>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="flex__column">
                    <div class="dl-link">
                        <span class="dl-link__text">Web Design — </span>
                        <span class="dl-link__link">
                            <a href="https://directlinedev.com/"
                               target="_blank"
                               rel="noopener noreferrer">Direct Line Development</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

src/apps_common/menu/templates/menu/menu.html
    <ul {% if level == 1 %}typeof="SiteNavigationElement"{% endif %} class="menu{% if level == 1 %} menu--{{ classes }}{% endif %}">
        {% for item in items %}
            {# item.is_active - true on all inner urls #}
            {# item.is_active_nolink true on inner url #}
            <li class="menu__item{% if item.is_active or item.is_active_nolink %} active{% endif %} {{ item.parent_classes }} {% if level == 1 %}general-item{% endif %}"{% if item.item_id %} id="{{ item.item_id }}{% if item_id_mod %}--{{ item_id_mod }}{% endif %}"{% endif %} >
                {% if item.is_active_nolink and item.url %}
                    <a href="{{ item.url }}" class="{{ item.classes }} item-caption" property="url" {{ item.attrs }}>
                        <span property="name" class="menu__name">{{ item.title }}</span>
                        {% if item.childs %}
                            <span class="menu__toggle"></span>
                        {% endif %}
                    </a>
                {% elif item.is_active or not item.url %}
                    <div class="{{ item.classes }} item-caption">
                        <span property="name" class="menu__name">{{ item.title }}</span>
                        {% if item.childs %}
                            <span class="menu__toggle"></span>
                        {% endif %}
                    </div>
                {% else %}
                    <a href="{{ item.url }}" class="{{ item.classes }} item-caption" property="url" {{ item.attrs }}>
                        <span property="name" class="menu__name">{{ item.title }}</span>
                        {% if item.childs %}
                            <span class="menu__toggle"></span>
                        {% endif %}
                    </a>
                {% endif %}
                {% if item.childs %}
                    {% with items=item.childs, level=level + 1 %}
                        <div class="menu-inner">
                            {% include 'menu/menu.html' %}
                        </div>
                    {% endwith %}
                {% endif %}
            </li>
        {% endfor %}
    </ul>

src/templates/suit/change_form.html
{% extends 'admin/change_form.html' %}

{% block extrajs %}
  {{ block.super }}

  {% if suit_tabs %}
    <script>
      (function($) {
        $(function() {
          $('#suit_form_tabs').suit_form_tabs();
        });
      }(Suit.$))
    </script>
  {% endif %}
{% endblock extrajs %}

{% block field_sets %}
  {% for fieldset in adminform %}
    {% if fieldset.fields %}
      {% include "admin/includes/fieldset.html" %}
    {% endif %}
  {% endfor %}
{% endblock field_sets %}

{% block suit_form_tabs %}
  {% if suit_tabs %}
    <ul id="suit_form_tabs" class="nav nav-tabs nav-tabs-suit" data-tab-prefix="suit-tab">
      {% for tab in suit_tabs %}
        <li><a href="#{{ tab.0 }}">{{ tab.1 }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock suit_form_tabs %}

src/templates/suit/menu.html
{#{% load sitetree %}#}
{% load i18n my_suit_menu %}
{% load url from suit_compat %}

<div class="left-nav" id="left-nav">
  <ul>
    {% block menu_home %}
      {% url 'admin:index' as index_url %}
      <li{% if index_url == request.path %} class="active"{% endif %}>
        <a href="{{ index_url }}"><i class="icon-home"></i>{% trans 'Welcome' %}
        </a>
      </li>
    {% endblock %}

    {% get_menu request as app_list %}
    {% if app_list %}
      {% for app in app_list %}
        {% if app.separator %}
          <li class="separator"></li>
        {% else %}
          <li{{ app.is_active|yesno:' class=active,' }}>
            <a href="{{ app.url }}"{{ app.blank|yesno:' target=_blank,' }}>
              <i class="{% firstof app.icon 'icon-chevron-right' %}"></i>
              {% trans app.label|capfirst %}
            </a>

            {% if app.models %}
              {% include 'suit/submenu.html' with models=app.models %}
            {% endif %}

          </li>
        {% endif %}
      {% endfor %}
    {% endif %}
  </ul>
</div>

src/templates/suit/submenu.html
<ul>
  {% for model in models %}
    <li{{ model.is_active|yesno:' class=active,' }}>
      <a href="{{ model.url }}"{{ model.blank|yesno:' target=_blank,' }}>{{ model.label }}</a>

      {% if model.models %}
        {% include 'suit/submenu.html' with models=model.models %}
      {% endif %}
    </li>
  {% endfor %}
</ul>